# Updated:   2026-01-25

services:
  fuseki:
    image: meshcz-fuseki
    container_name: meshcz-fuseki
    ports:
      - "3030:3030"
    networks:
      - meshnet

  skosmos:
    image: meshcz-skosmos
    container_name: meshcz-skosmos
    ports:
      - "8080:80"
    depends_on:
      - fuseki
    networks:
      - meshnet

networks:
  meshnet:
    driver: bridge
